

#import "DRCTSGetTableColumnsDataManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

@implementation DRCTSGetTableColumnsDataManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(DRCTSGetTableColumnsDataManagedObject*)createNewDRCTSGetTableColumnsDataManagedObjectInContext:(NSManagedObjectContext*)context {
    DRCTSGetTableColumnsDataManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([DRCTSGetTableColumnsDataManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(DRCTSGetTableColumnsDataManagedObject*)DRCTSGetTableColumnsDataManagedObjectFromDRCTSGetTableColumnsData:(DRCTSGetTableColumnsData*)object context:(NSManagedObjectContext*)context {
    DRCTSGetTableColumnsDataManagedObject* newDRCTSGetTableColumnsData = [self createNewDRCTSGetTableColumnsDataManagedObjectInContext:context];
    [self updateDRCTSGetTableColumnsDataManagedObject:newDRCTSGetTableColumnsData withDRCTSGetTableColumnsData:object];
    return newDRCTSGetTableColumnsData;
}

-(void)updateDRCTSGetTableColumnsDataManagedObject:(DRCTSGetTableColumnsDataManagedObject*)managedObject withDRCTSGetTableColumnsData:(DRCTSGetTableColumnsData*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.name = [object.name copy];
    managedObject._id = [object._id copy];
    managedObject.columnName = [object.columnName copy];
    managedObject.type = [object.type copy];
    managedObject.length = [object.length copy];
    managedObject.precision = [object.precision copy];
    managedObject.scale = [object.scale copy];
    managedObject.sort = [object.sort copy];
    managedObject.defaultValue = [object.defaultValue copy];
    managedObject.nullable = [object.nullable copy];
    managedObject.key = [object.key copy];
    managedObject.extraOptions = [object.extraOptions copy];
    managedObject.options = [object.options copy];
    managedObject.tableName = [object.tableName copy];
    managedObject.required = [object.required copy];
    managedObject.ui = [object.ui copy];
    managedObject.hiddenList = [object.hiddenList copy];
    managedObject.hiddenInput = [object.hiddenInput copy];
    managedObject.relationship = [object.relationship copy];
    managedObject.comment = [object.comment copy];

}

-(DRCTSGetTableColumnsData*)DRCTSGetTableColumnsDataFromDRCTSGetTableColumnsDataManagedObject:(DRCTSGetTableColumnsDataManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    DRCTSGetTableColumnsData* newDRCTSGetTableColumnsData = [[DRCTSGetTableColumnsData alloc] init];
    [self updateDRCTSGetTableColumnsData:newDRCTSGetTableColumnsData withDRCTSGetTableColumnsDataManagedObject:obj];
    return newDRCTSGetTableColumnsData;
}

-(void)updateDRCTSGetTableColumnsData:(DRCTSGetTableColumnsData*)newDRCTSGetTableColumnsData withDRCTSGetTableColumnsDataManagedObject:(DRCTSGetTableColumnsDataManagedObject*)obj {
    newDRCTSGetTableColumnsData.name = [obj.name copy];
    newDRCTSGetTableColumnsData._id = [obj._id copy];
    newDRCTSGetTableColumnsData.columnName = [obj.columnName copy];
    newDRCTSGetTableColumnsData.type = [obj.type copy];
    newDRCTSGetTableColumnsData.length = [obj.length copy];
    newDRCTSGetTableColumnsData.precision = [obj.precision copy];
    newDRCTSGetTableColumnsData.scale = [obj.scale copy];
    newDRCTSGetTableColumnsData.sort = [obj.sort copy];
    newDRCTSGetTableColumnsData.defaultValue = [obj.defaultValue copy];
    newDRCTSGetTableColumnsData.nullable = [obj.nullable copy];
    newDRCTSGetTableColumnsData.key = [obj.key copy];
    newDRCTSGetTableColumnsData.extraOptions = [obj.extraOptions copy];
    newDRCTSGetTableColumnsData.options = [obj.options copy];
    newDRCTSGetTableColumnsData.tableName = [obj.tableName copy];
    newDRCTSGetTableColumnsData.required = [obj.required copy];
    newDRCTSGetTableColumnsData.ui = [obj.ui copy];
    newDRCTSGetTableColumnsData.hiddenList = [obj.hiddenList copy];
    newDRCTSGetTableColumnsData.hiddenInput = [obj.hiddenInput copy];
    newDRCTSGetTableColumnsData.relationship = [obj.relationship copy];
    newDRCTSGetTableColumnsData.comment = [obj.comment copy];
}

@end
