#import "DRCTSGetTableManagedObject.h"

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/
@implementation DRCTSGetTableManagedObject

@dynamic meta;
@dynamic data;
@end
