#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

#import "DRCTSGetPrivilegesDataManagedObjectBuilder.h"
#import "DRCTSGetTablesMetaManagedObjectBuilder.h"

#import "DRCTSGetPrivilegesForTableManagedObject.h"
#import "DRCTSGetPrivilegesForTable.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface DRCTSGetPrivilegesForTableManagedObjectBuilder : NSObject

@property (nonatomic, strong) DRCTSGetTablesMetaManagedObjectBuilder * metaBuilder;
@property (nonatomic, strong) DRCTSGetPrivilegesDataManagedObjectBuilder * dataBuilder;


-(DRCTSGetPrivilegesForTableManagedObject*)createNewDRCTSGetPrivilegesForTableManagedObjectInContext:(NSManagedObjectContext*)context;

-(DRCTSGetPrivilegesForTableManagedObject*)DRCTSGetPrivilegesForTableManagedObjectFromDRCTSGetPrivilegesForTable:(DRCTSGetPrivilegesForTable*)object context:(NSManagedObjectContext*)context;

-(void)updateDRCTSGetPrivilegesForTableManagedObject:(DRCTSGetPrivilegesForTableManagedObject*)object withDRCTSGetPrivilegesForTable:(DRCTSGetPrivilegesForTable*)object2;

-(DRCTSGetPrivilegesForTable*)DRCTSGetPrivilegesForTableFromDRCTSGetPrivilegesForTableManagedObject:(DRCTSGetPrivilegesForTableManagedObject*)obj;

-(void)updateDRCTSGetPrivilegesForTable:(DRCTSGetPrivilegesForTable*)object withDRCTSGetPrivilegesForTableManagedObject:(DRCTSGetPrivilegesForTableManagedObject*)object2;

@end
