#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




NS_ASSUME_NONNULL_BEGIN

@interface DRCTSGetActivityDataManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSNumber* _id;

@property (nullable, nonatomic, retain) NSString* identifier;

@property (nullable, nonatomic, retain) NSString* action;

@property (nullable, nonatomic, retain) NSString* tableName;

@property (nullable, nonatomic, retain) NSNumber* rowId;

@property (nullable, nonatomic, retain) NSString* user;

@property (nullable, nonatomic, retain) NSString* datetime;

@property (nullable, nonatomic, retain) NSString* type;

@property (nullable, nonatomic, retain) NSString* data;
@end

@interface DRCTSGetActivityDataManagedObject (GeneratedAccessors)

@end


NS_ASSUME_NONNULL_END
