#import "DRCTSGetTableColumnsDataManagedObject.h"

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/
@implementation DRCTSGetTableColumnsDataManagedObject

@dynamic name;
@dynamic _id;
@dynamic columnName;
@dynamic type;
@dynamic length;
@dynamic precision;
@dynamic scale;
@dynamic sort;
@dynamic defaultValue;
@dynamic nullable;
@dynamic key;
@dynamic extraOptions;
@dynamic options;
@dynamic tableName;
@dynamic required;
@dynamic ui;
@dynamic hiddenList;
@dynamic hiddenInput;
@dynamic relationship;
@dynamic comment;
@end
