#import <Foundation/Foundation.h>
#import "DRCTSObject.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DRCTSGetTableColumnData.h"
#import "DRCTSGetTablesMeta.h"
@protocol DRCTSGetTableColumnData;
@class DRCTSGetTableColumnData;
@protocol DRCTSGetTablesMeta;
@class DRCTSGetTablesMeta;



@protocol DRCTSGetTableColumn
@end

@interface DRCTSGetTableColumn : DRCTSObject


@property(nonatomic) DRCTSGetTablesMeta* meta;

@property(nonatomic) DRCTSGetTableColumnData* data;

@end
