#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "DRCTSGetGroupsDataMetaManagedObject.h"
#import "DRCTSGetGroupsDataMeta.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface DRCTSGetGroupsDataMetaManagedObjectBuilder : NSObject



-(DRCTSGetGroupsDataMetaManagedObject*)createNewDRCTSGetGroupsDataMetaManagedObjectInContext:(NSManagedObjectContext*)context;

-(DRCTSGetGroupsDataMetaManagedObject*)DRCTSGetGroupsDataMetaManagedObjectFromDRCTSGetGroupsDataMeta:(DRCTSGetGroupsDataMeta*)object context:(NSManagedObjectContext*)context;

-(void)updateDRCTSGetGroupsDataMetaManagedObject:(DRCTSGetGroupsDataMetaManagedObject*)object withDRCTSGetGroupsDataMeta:(DRCTSGetGroupsDataMeta*)object2;

-(DRCTSGetGroupsDataMeta*)DRCTSGetGroupsDataMetaFromDRCTSGetGroupsDataMetaManagedObject:(DRCTSGetGroupsDataMetaManagedObject*)obj;

-(void)updateDRCTSGetGroupsDataMeta:(DRCTSGetGroupsDataMeta*)object withDRCTSGetGroupsDataMetaManagedObject:(DRCTSGetGroupsDataMetaManagedObject*)object2;

@end
