

#import "DRCTSGetPreferencesDataManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

@implementation DRCTSGetPreferencesDataManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(DRCTSGetPreferencesDataManagedObject*)createNewDRCTSGetPreferencesDataManagedObjectInContext:(NSManagedObjectContext*)context {
    DRCTSGetPreferencesDataManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([DRCTSGetPreferencesDataManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(DRCTSGetPreferencesDataManagedObject*)DRCTSGetPreferencesDataManagedObjectFromDRCTSGetPreferencesData:(DRCTSGetPreferencesData*)object context:(NSManagedObjectContext*)context {
    DRCTSGetPreferencesDataManagedObject* newDRCTSGetPreferencesData = [self createNewDRCTSGetPreferencesDataManagedObjectInContext:context];
    [self updateDRCTSGetPreferencesDataManagedObject:newDRCTSGetPreferencesData withDRCTSGetPreferencesData:object];
    return newDRCTSGetPreferencesData;
}

-(void)updateDRCTSGetPreferencesDataManagedObject:(DRCTSGetPreferencesDataManagedObject*)managedObject withDRCTSGetPreferencesData:(DRCTSGetPreferencesData*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject._id = [object._id copy];
    managedObject.user = [object.user copy];
    managedObject.tableName = [object.tableName copy];
    managedObject.title = [object.title copy];
    managedObject.columnsVisible = [object.columnsVisible copy];
    managedObject.sort = [object.sort copy];
    managedObject.sortOrder = [object.sortOrder copy];
    managedObject.status = [object.status copy];
    managedObject.searchString = [object.searchString copy];

}

-(DRCTSGetPreferencesData*)DRCTSGetPreferencesDataFromDRCTSGetPreferencesDataManagedObject:(DRCTSGetPreferencesDataManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    DRCTSGetPreferencesData* newDRCTSGetPreferencesData = [[DRCTSGetPreferencesData alloc] init];
    [self updateDRCTSGetPreferencesData:newDRCTSGetPreferencesData withDRCTSGetPreferencesDataManagedObject:obj];
    return newDRCTSGetPreferencesData;
}

-(void)updateDRCTSGetPreferencesData:(DRCTSGetPreferencesData*)newDRCTSGetPreferencesData withDRCTSGetPreferencesDataManagedObject:(DRCTSGetPreferencesDataManagedObject*)obj {
    newDRCTSGetPreferencesData._id = [obj._id copy];
    newDRCTSGetPreferencesData.user = [obj.user copy];
    newDRCTSGetPreferencesData.tableName = [obj.tableName copy];
    newDRCTSGetPreferencesData.title = [obj.title copy];
    newDRCTSGetPreferencesData.columnsVisible = [obj.columnsVisible copy];
    newDRCTSGetPreferencesData.sort = [obj.sort copy];
    newDRCTSGetPreferencesData.sortOrder = [obj.sortOrder copy];
    newDRCTSGetPreferencesData.status = [obj.status copy];
    newDRCTSGetPreferencesData.searchString = [obj.searchString copy];
}

@end
