#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "DRCTSGetTableColumnDataManagedObject.h"
#import "DRCTSGetTableColumnData.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface DRCTSGetTableColumnDataManagedObjectBuilder : NSObject



-(DRCTSGetTableColumnDataManagedObject*)createNewDRCTSGetTableColumnDataManagedObjectInContext:(NSManagedObjectContext*)context;

-(DRCTSGetTableColumnDataManagedObject*)DRCTSGetTableColumnDataManagedObjectFromDRCTSGetTableColumnData:(DRCTSGetTableColumnData*)object context:(NSManagedObjectContext*)context;

-(void)updateDRCTSGetTableColumnDataManagedObject:(DRCTSGetTableColumnDataManagedObject*)object withDRCTSGetTableColumnData:(DRCTSGetTableColumnData*)object2;

-(DRCTSGetTableColumnData*)DRCTSGetTableColumnDataFromDRCTSGetTableColumnDataManagedObject:(DRCTSGetTableColumnDataManagedObject*)obj;

-(void)updateDRCTSGetTableColumnData:(DRCTSGetTableColumnData*)object withDRCTSGetTableColumnDataManagedObject:(DRCTSGetTableColumnDataManagedObject*)object2;

@end
