#import <Foundation/Foundation.h>
#import "DRCTSObject.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DRCTSGetSettingsDataGlobal.h"
#import "DRCTSGetSettingsForMeta.h"
@protocol DRCTSGetSettingsDataGlobal;
@class DRCTSGetSettingsDataGlobal;
@protocol DRCTSGetSettingsForMeta;
@class DRCTSGetSettingsForMeta;



@protocol DRCTSGetSettingsFor
@end

@interface DRCTSGetSettingsFor : DRCTSObject


@property(nonatomic) DRCTSGetSettingsForMeta* meta;

@property(nonatomic) DRCTSGetSettingsDataGlobal* data;

@end
