#import "DRCTSGetFilesDataManagedObject.h"

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/
@implementation DRCTSGetFilesDataManagedObject

@dynamic _id;
@dynamic active;
@dynamic name;
@dynamic url;
@dynamic title;
@dynamic location;
@dynamic caption;
@dynamic type;
@dynamic charset;
@dynamic tags;
@dynamic width;
@dynamic height;
@dynamic size;
@dynamic embedId;
@dynamic user;
@dynamic dateUploaded;
@dynamic storageAdapter;
@end
