

#import "DRCTSGetBookmarksDataManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

@implementation DRCTSGetBookmarksDataManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(DRCTSGetBookmarksDataManagedObject*)createNewDRCTSGetBookmarksDataManagedObjectInContext:(NSManagedObjectContext*)context {
    DRCTSGetBookmarksDataManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([DRCTSGetBookmarksDataManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(DRCTSGetBookmarksDataManagedObject*)DRCTSGetBookmarksDataManagedObjectFromDRCTSGetBookmarksData:(DRCTSGetBookmarksData*)object context:(NSManagedObjectContext*)context {
    DRCTSGetBookmarksDataManagedObject* newDRCTSGetBookmarksData = [self createNewDRCTSGetBookmarksDataManagedObjectInContext:context];
    [self updateDRCTSGetBookmarksDataManagedObject:newDRCTSGetBookmarksData withDRCTSGetBookmarksData:object];
    return newDRCTSGetBookmarksData;
}

-(void)updateDRCTSGetBookmarksDataManagedObject:(DRCTSGetBookmarksDataManagedObject*)managedObject withDRCTSGetBookmarksData:(DRCTSGetBookmarksData*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject._id = [object._id copy];
    managedObject.user = [object.user copy];
    managedObject.title = [object.title copy];
    managedObject.url = [object.url copy];
    managedObject.iconClass = [object.iconClass copy];
    managedObject.active = [object.active copy];
    managedObject.section = [object.section copy];

}

-(DRCTSGetBookmarksData*)DRCTSGetBookmarksDataFromDRCTSGetBookmarksDataManagedObject:(DRCTSGetBookmarksDataManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    DRCTSGetBookmarksData* newDRCTSGetBookmarksData = [[DRCTSGetBookmarksData alloc] init];
    [self updateDRCTSGetBookmarksData:newDRCTSGetBookmarksData withDRCTSGetBookmarksDataManagedObject:obj];
    return newDRCTSGetBookmarksData;
}

-(void)updateDRCTSGetBookmarksData:(DRCTSGetBookmarksData*)newDRCTSGetBookmarksData withDRCTSGetBookmarksDataManagedObject:(DRCTSGetBookmarksDataManagedObject*)obj {
    newDRCTSGetBookmarksData._id = [obj._id copy];
    newDRCTSGetBookmarksData.user = [obj.user copy];
    newDRCTSGetBookmarksData.title = [obj.title copy];
    newDRCTSGetBookmarksData.url = [obj.url copy];
    newDRCTSGetBookmarksData.iconClass = [obj.iconClass copy];
    newDRCTSGetBookmarksData.active = [obj.active copy];
    newDRCTSGetBookmarksData.section = [obj.section copy];
}

@end
