#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DRCTSGetActivityDataManagedObject.h"
#import "DRCTSGetActivityMetaManagedObject.h"


NS_ASSUME_NONNULL_BEGIN

@interface DRCTSGetActivityManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) DRCTSGetActivityMetaManagedObject* meta;

@property (nullable, nonatomic, retain) NSOrderedSet<DRCTSGetActivityDataManagedObject*>* data;
@end

@interface DRCTSGetActivityManagedObject (GeneratedAccessors)
- (void)addDataObject:(DRCTSGetActivityDataManagedObject *)value;
- (void)removeDataObject:(DRCTSGetActivityDataManagedObject *)value;
- (void)addData:(NSOrderedSet<DRCTSGetActivityDataManagedObject*> *)values;
- (void)removeData:(NSOrderedSet<DRCTSGetActivityDataManagedObject*> *)values;

@end


NS_ASSUME_NONNULL_END
