#import <Foundation/Foundation.h>
#import "DRCTSObject.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DRCTSGetTableRowsData.h"
#import "DRCTSGetTableRowsMeta.h"
@protocol DRCTSGetTableRowsData;
@class DRCTSGetTableRowsData;
@protocol DRCTSGetTableRowsMeta;
@class DRCTSGetTableRowsMeta;



@protocol DRCTSGetTableRows
@end

@interface DRCTSGetTableRows : DRCTSObject


@property(nonatomic) DRCTSGetTableRowsMeta* meta;

@property(nonatomic) NSArray<DRCTSGetTableRowsData>* data;

@end
