#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "DRCTSGetActivityMetaManagedObject.h"
#import "DRCTSGetActivityMeta.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface DRCTSGetActivityMetaManagedObjectBuilder : NSObject



-(DRCTSGetActivityMetaManagedObject*)createNewDRCTSGetActivityMetaManagedObjectInContext:(NSManagedObjectContext*)context;

-(DRCTSGetActivityMetaManagedObject*)DRCTSGetActivityMetaManagedObjectFromDRCTSGetActivityMeta:(DRCTSGetActivityMeta*)object context:(NSManagedObjectContext*)context;

-(void)updateDRCTSGetActivityMetaManagedObject:(DRCTSGetActivityMetaManagedObject*)object withDRCTSGetActivityMeta:(DRCTSGetActivityMeta*)object2;

-(DRCTSGetActivityMeta*)DRCTSGetActivityMetaFromDRCTSGetActivityMetaManagedObject:(DRCTSGetActivityMetaManagedObject*)obj;

-(void)updateDRCTSGetActivityMeta:(DRCTSGetActivityMeta*)object withDRCTSGetActivityMetaManagedObject:(DRCTSGetActivityMetaManagedObject*)object2;

@end
