#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

#import "DRCTSGetFilesDataManagedObjectBuilder.h"
#import "DRCTSGetTablesMetaManagedObjectBuilder.h"

#import "DRCTSGetFilesManagedObject.h"
#import "DRCTSGetFiles.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface DRCTSGetFilesManagedObjectBuilder : NSObject

@property (nonatomic, strong) DRCTSGetTablesMetaManagedObjectBuilder * metaBuilder;
@property (nonatomic, strong) DRCTSGetFilesDataManagedObjectBuilder * dataBuilder;


-(DRCTSGetFilesManagedObject*)createNewDRCTSGetFilesManagedObjectInContext:(NSManagedObjectContext*)context;

-(DRCTSGetFilesManagedObject*)DRCTSGetFilesManagedObjectFromDRCTSGetFiles:(DRCTSGetFiles*)object context:(NSManagedObjectContext*)context;

-(void)updateDRCTSGetFilesManagedObject:(DRCTSGetFilesManagedObject*)object withDRCTSGetFiles:(DRCTSGetFiles*)object2;

-(DRCTSGetFiles*)DRCTSGetFilesFromDRCTSGetFilesManagedObject:(DRCTSGetFilesManagedObject*)obj;

-(void)updateDRCTSGetFiles:(DRCTSGetFiles*)object withDRCTSGetFilesManagedObject:(DRCTSGetFilesManagedObject*)object2;

@end
