#import <Foundation/Foundation.h>
#import "DRCTSObject.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol DRCTSGetPreferencesData
@end

@interface DRCTSGetPreferencesData : DRCTSObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSNumber* user;

@property(nonatomic) NSString* tableName;

@property(nonatomic) NSString* title;

@property(nonatomic) NSString* columnsVisible;

@property(nonatomic) NSString* sort;

@property(nonatomic) NSString* sortOrder;

@property(nonatomic) NSString* status;

@property(nonatomic) NSString* searchString;

@end
