#import "DRCTSGetPreferencesDataManagedObject.h"

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/
@implementation DRCTSGetPreferencesDataManagedObject

@dynamic _id;
@dynamic user;
@dynamic tableName;
@dynamic title;
@dynamic columnsVisible;
@dynamic sort;
@dynamic sortOrder;
@dynamic status;
@dynamic searchString;
@end
