#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




NS_ASSUME_NONNULL_BEGIN

@interface DRCTSGetPrivilegesDataManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSNumber* _id;

@property (nullable, nonatomic, retain) NSString* tableName;

@property (nullable, nonatomic, retain) NSNumber* groupId;

@property (nullable, nonatomic, retain) NSString* readFieldBlacklist;

@property (nullable, nonatomic, retain) NSString* writeFieldBlacklist;

@property (nullable, nonatomic, retain) NSNumber* navListed;

@property (nullable, nonatomic, retain) NSNumber* statusId;

@property (nullable, nonatomic, retain) NSNumber* allowView;

@property (nullable, nonatomic, retain) NSNumber* allowAdd;

@property (nullable, nonatomic, retain) NSNumber* allowEdit;

@property (nullable, nonatomic, retain) NSNumber* allowDelete;

@property (nullable, nonatomic, retain) NSNumber* allowAlter;
@end

@interface DRCTSGetPrivilegesDataManagedObject (GeneratedAccessors)

@end


NS_ASSUME_NONNULL_END
