#import <Foundation/Foundation.h>
#import "DRCTSObject.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol DRCTSGetTableColumnData
@end

@interface DRCTSGetTableColumnData : DRCTSObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* columnName;

@property(nonatomic) NSString* type;

@property(nonatomic) NSString* charLength;

@property(nonatomic) NSString* isNullable;

@property(nonatomic) NSString* comment;

@property(nonatomic) NSNumber* sort;

@property(nonatomic) NSNumber* system;

@property(nonatomic) NSNumber* master;

@property(nonatomic) NSNumber* hiddenList;

@property(nonatomic) NSNumber* hiddenInput;

@property(nonatomic) NSNumber* required;

@property(nonatomic) NSString* columnType;

@property(nonatomic) NSNumber* isWritable;

@property(nonatomic) NSString* ui;

@property(nonatomic) NSArray<NSObject*>* options;

@end
