#import <Foundation/Foundation.h>
#import "DRCTSObject.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol DRCTSGetTableData
@end

@interface DRCTSGetTableData : DRCTSObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* tableName;

@property(nonatomic) NSArray<NSObject*>* columns;

@property(nonatomic) NSObject* preferences;

@property(nonatomic) NSString* primaryColumn;

@property(nonatomic) NSString* schema;

@property(nonatomic) NSNumber* hidden;

@property(nonatomic) NSNumber* single;

@property(nonatomic) NSString* defaultStatus;

@property(nonatomic) NSString* userCreateColumn;

@property(nonatomic) NSString* userUpdateColumn;

@property(nonatomic) NSString* dateCreateColumn;

@property(nonatomic) NSString* dateUpdateColumn;

@property(nonatomic) NSString* createdAt;

@property(nonatomic) NSString* dateCreated;

@property(nonatomic) NSString* comment;

@property(nonatomic) NSNumber* rowCount;

@property(nonatomic) NSNumber* footer;

@property(nonatomic) NSString* listView;

@property(nonatomic) NSString* columnGroupings;

@property(nonatomic) NSString* filterColumnBlacklist;

@end
