#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "DRCTSGetSettingsForMetaManagedObject.h"
#import "DRCTSGetSettingsForMeta.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface DRCTSGetSettingsForMetaManagedObjectBuilder : NSObject



-(DRCTSGetSettingsForMetaManagedObject*)createNewDRCTSGetSettingsForMetaManagedObjectInContext:(NSManagedObjectContext*)context;

-(DRCTSGetSettingsForMetaManagedObject*)DRCTSGetSettingsForMetaManagedObjectFromDRCTSGetSettingsForMeta:(DRCTSGetSettingsForMeta*)object context:(NSManagedObjectContext*)context;

-(void)updateDRCTSGetSettingsForMetaManagedObject:(DRCTSGetSettingsForMetaManagedObject*)object withDRCTSGetSettingsForMeta:(DRCTSGetSettingsForMeta*)object2;

-(DRCTSGetSettingsForMeta*)DRCTSGetSettingsForMetaFromDRCTSGetSettingsForMetaManagedObject:(DRCTSGetSettingsForMetaManagedObject*)obj;

-(void)updateDRCTSGetSettingsForMeta:(DRCTSGetSettingsForMeta*)object withDRCTSGetSettingsForMetaManagedObject:(DRCTSGetSettingsForMetaManagedObject*)object2;

@end
