#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

#import "DRCTSGetFilesDataManagedObjectBuilder.h"
#import "DRCTSGetTablesMetaManagedObjectBuilder.h"

#import "DRCTSGetFileManagedObject.h"
#import "DRCTSGetFile.h"

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface DRCTSGetFileManagedObjectBuilder : NSObject

@property (nonatomic, strong) DRCTSGetTablesMetaManagedObjectBuilder * metaBuilder;
@property (nonatomic, strong) DRCTSGetFilesDataManagedObjectBuilder * dataBuilder;


-(DRCTSGetFileManagedObject*)createNewDRCTSGetFileManagedObjectInContext:(NSManagedObjectContext*)context;

-(DRCTSGetFileManagedObject*)DRCTSGetFileManagedObjectFromDRCTSGetFile:(DRCTSGetFile*)object context:(NSManagedObjectContext*)context;

-(void)updateDRCTSGetFileManagedObject:(DRCTSGetFileManagedObject*)object withDRCTSGetFile:(DRCTSGetFile*)object2;

-(DRCTSGetFile*)DRCTSGetFileFromDRCTSGetFileManagedObject:(DRCTSGetFileManagedObject*)obj;

-(void)updateDRCTSGetFile:(DRCTSGetFile*)object withDRCTSGetFileManagedObject:(DRCTSGetFileManagedObject*)object2;

@end
