/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Directus.Api;
using IO.Directus.Model;
using IO.Directus.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Directus.Test
{
    /// <summary>
    ///  Class for testing GetBookmarksMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetBookmarksMetaTests
    {
        // TODO uncomment below to declare an instance variable for GetBookmarksMeta
        //private GetBookmarksMeta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetBookmarksMeta
            //instance = new GetBookmarksMeta();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetBookmarksMeta
        /// </summary>
        [Test]
        public void GetBookmarksMetaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetBookmarksMeta
            //Assert.IsInstanceOfType<GetBookmarksMeta> (instance, "variable 'instance' is a GetBookmarksMeta");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Table'
        /// </summary>
        [Test]
        public void TableTest()
        {
            // TODO unit test for the property 'Table'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Delete'
        /// </summary>
        [Test]
        public void DeleteTest()
        {
            // TODO unit test for the property 'Delete'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Draft'
        /// </summary>
        [Test]
        public void DraftTest()
        {
            // TODO unit test for the property 'Draft'
        }
        /// <summary>
        /// Test the property 'TotalEntries'
        /// </summary>
        [Test]
        public void TotalEntriesTest()
        {
            // TODO unit test for the property 'TotalEntries'
        }

    }

}
