/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Directus.Api;
using IO.Directus.Model;
using IO.Directus.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Directus.Test
{
    /// <summary>
    ///  Class for testing GetSettingsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetSettingsDataTests
    {
        // TODO uncomment below to declare an instance variable for GetSettingsData
        //private GetSettingsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetSettingsData
            //instance = new GetSettingsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetSettingsData
        /// </summary>
        [Test]
        public void GetSettingsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetSettingsData
            //Assert.IsInstanceOfType<GetSettingsData> (instance, "variable 'instance' is a GetSettingsData");
        }


        /// <summary>
        /// Test the property 'Global'
        /// </summary>
        [Test]
        public void GlobalTest()
        {
            // TODO unit test for the property 'Global'
        }
        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Test]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }

    }

}
