/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Directus.Api;
using IO.Directus.Model;
using IO.Directus.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Directus.Test
{
    /// <summary>
    ///  Class for testing GetSettingsDataGlobal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetSettingsDataGlobalTests
    {
        // TODO uncomment below to declare an instance variable for GetSettingsDataGlobal
        //private GetSettingsDataGlobal instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetSettingsDataGlobal
            //instance = new GetSettingsDataGlobal();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetSettingsDataGlobal
        /// </summary>
        [Test]
        public void GetSettingsDataGlobalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetSettingsDataGlobal
            //Assert.IsInstanceOfType<GetSettingsDataGlobal> (instance, "variable 'instance' is a GetSettingsDataGlobal");
        }


        /// <summary>
        /// Test the property 'CmsUserAutoSignOut'
        /// </summary>
        [Test]
        public void CmsUserAutoSignOutTest()
        {
            // TODO unit test for the property 'CmsUserAutoSignOut'
        }
        /// <summary>
        /// Test the property 'ProjectName'
        /// </summary>
        [Test]
        public void ProjectNameTest()
        {
            // TODO unit test for the property 'ProjectName'
        }
        /// <summary>
        /// Test the property 'ProjectUrl'
        /// </summary>
        [Test]
        public void ProjectUrlTest()
        {
            // TODO unit test for the property 'ProjectUrl'
        }
        /// <summary>
        /// Test the property 'CmsColor'
        /// </summary>
        [Test]
        public void CmsColorTest()
        {
            // TODO unit test for the property 'CmsColor'
        }
        /// <summary>
        /// Test the property 'RowsPerPage'
        /// </summary>
        [Test]
        public void RowsPerPageTest()
        {
            // TODO unit test for the property 'RowsPerPage'
        }
        /// <summary>
        /// Test the property 'CmsThumbnailUrl'
        /// </summary>
        [Test]
        public void CmsThumbnailUrlTest()
        {
            // TODO unit test for the property 'CmsThumbnailUrl'
        }

    }

}
