/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Directus.Api;
using IO.Directus.Model;
using IO.Directus.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Directus.Test
{
    /// <summary>
    ///  Class for testing GetTableData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTableDataTests
    {
        // TODO uncomment below to declare an instance variable for GetTableData
        //private GetTableData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTableData
            //instance = new GetTableData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTableData
        /// </summary>
        [Test]
        public void GetTableDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTableData
            //Assert.IsInstanceOfType<GetTableData> (instance, "variable 'instance' is a GetTableData");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TableName'
        /// </summary>
        [Test]
        public void TableNameTest()
        {
            // TODO unit test for the property 'TableName'
        }
        /// <summary>
        /// Test the property 'Columns'
        /// </summary>
        [Test]
        public void ColumnsTest()
        {
            // TODO unit test for the property 'Columns'
        }
        /// <summary>
        /// Test the property 'Preferences'
        /// </summary>
        [Test]
        public void PreferencesTest()
        {
            // TODO unit test for the property 'Preferences'
        }
        /// <summary>
        /// Test the property 'PrimaryColumn'
        /// </summary>
        [Test]
        public void PrimaryColumnTest()
        {
            // TODO unit test for the property 'PrimaryColumn'
        }
        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Test]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }
        /// <summary>
        /// Test the property 'Hidden'
        /// </summary>
        [Test]
        public void HiddenTest()
        {
            // TODO unit test for the property 'Hidden'
        }
        /// <summary>
        /// Test the property 'Single'
        /// </summary>
        [Test]
        public void SingleTest()
        {
            // TODO unit test for the property 'Single'
        }
        /// <summary>
        /// Test the property 'DefaultStatus'
        /// </summary>
        [Test]
        public void DefaultStatusTest()
        {
            // TODO unit test for the property 'DefaultStatus'
        }
        /// <summary>
        /// Test the property 'UserCreateColumn'
        /// </summary>
        [Test]
        public void UserCreateColumnTest()
        {
            // TODO unit test for the property 'UserCreateColumn'
        }
        /// <summary>
        /// Test the property 'UserUpdateColumn'
        /// </summary>
        [Test]
        public void UserUpdateColumnTest()
        {
            // TODO unit test for the property 'UserUpdateColumn'
        }
        /// <summary>
        /// Test the property 'DateCreateColumn'
        /// </summary>
        [Test]
        public void DateCreateColumnTest()
        {
            // TODO unit test for the property 'DateCreateColumn'
        }
        /// <summary>
        /// Test the property 'DateUpdateColumn'
        /// </summary>
        [Test]
        public void DateUpdateColumnTest()
        {
            // TODO unit test for the property 'DateUpdateColumn'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Test]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Test]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'RowCount'
        /// </summary>
        [Test]
        public void RowCountTest()
        {
            // TODO unit test for the property 'RowCount'
        }
        /// <summary>
        /// Test the property 'Footer'
        /// </summary>
        [Test]
        public void FooterTest()
        {
            // TODO unit test for the property 'Footer'
        }
        /// <summary>
        /// Test the property 'ListView'
        /// </summary>
        [Test]
        public void ListViewTest()
        {
            // TODO unit test for the property 'ListView'
        }
        /// <summary>
        /// Test the property 'ColumnGroupings'
        /// </summary>
        [Test]
        public void ColumnGroupingsTest()
        {
            // TODO unit test for the property 'ColumnGroupings'
        }
        /// <summary>
        /// Test the property 'FilterColumnBlacklist'
        /// </summary>
        [Test]
        public void FilterColumnBlacklistTest()
        {
            // TODO unit test for the property 'FilterColumnBlacklist'
        }

    }

}
