/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Directus.Api;
using IO.Directus.Model;
using IO.Directus.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Directus.Test
{
    /// <summary>
    ///  Class for testing GetTableRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTableRowTests
    {
        // TODO uncomment below to declare an instance variable for GetTableRow
        //private GetTableRow instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTableRow
            //instance = new GetTableRow();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTableRow
        /// </summary>
        [Test]
        public void GetTableRowInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTableRow
            //Assert.IsInstanceOfType<GetTableRow> (instance, "variable 'instance' is a GetTableRow");
        }


        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Test]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
