=begin
#directus.io

#API for directus.io

OpenAPI spec version: 1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for DirectusSDK::SettingsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SettingsApi' do
  before do
    # run before each test
    @instance = DirectusSDK::SettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsApi' do
    it 'should create an instance of SettingsApi' do
      expect(@instance).to be_instance_of(DirectusSDK::SettingsApi)
    end
  end

  # unit tests for get_settings
  # Returns settings
  # 
  # @param [Hash] opts the optional parameters
  # @return [GetSettings]
  describe 'get_settings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_settings_for
  # Returns settings for collection
  # 
  # @param collection_name Name of collection to return settings for
  # @param [Hash] opts the optional parameters
  # @return [GetSettingsFor]
  describe 'get_settings_for test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_settings
  # Update settings
  # 
  # @param collection_name Name of collection to return settings for
  # @param custom_data Data based on your specific schema eg: active&#x3D;1&amp;title&#x3D;LoremIpsum
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_settings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
