=begin
#directus.io

#API for directus.io

OpenAPI spec version: 1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DirectusSDK::GetPreferences
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetPreferences' do
  before do
    # run before each test
    @instance = DirectusSDK::GetPreferences.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetPreferences' do
    it 'should create an instance of GetPreferences' do
      expect(@instance).to be_instance_of(DirectusSDK::GetPreferences)
    end
  end
  describe 'test attribute "meta"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

