/*
 * directus.io
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.directus.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetPreferencesData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T21:48:16.590Z")
public class GetPreferencesData {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("user")
  private Integer user = null;

  @SerializedName("table_name")
  private String tableName = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("columns_visible")
  private String columnsVisible = null;

  @SerializedName("sort")
  private String sort = null;

  @SerializedName("sort_order")
  private String sortOrder = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("search_string")
  private String searchString = null;

  public GetPreferencesData id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public GetPreferencesData user(Integer user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(value = "")
  public Integer getUser() {
    return user;
  }

  public void setUser(Integer user) {
    this.user = user;
  }

  public GetPreferencesData tableName(String tableName) {
    this.tableName = tableName;
    return this;
  }

   /**
   * Get tableName
   * @return tableName
  **/
  @ApiModelProperty(value = "")
  public String getTableName() {
    return tableName;
  }

  public void setTableName(String tableName) {
    this.tableName = tableName;
  }

  public GetPreferencesData title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public GetPreferencesData columnsVisible(String columnsVisible) {
    this.columnsVisible = columnsVisible;
    return this;
  }

   /**
   * Get columnsVisible
   * @return columnsVisible
  **/
  @ApiModelProperty(value = "")
  public String getColumnsVisible() {
    return columnsVisible;
  }

  public void setColumnsVisible(String columnsVisible) {
    this.columnsVisible = columnsVisible;
  }

  public GetPreferencesData sort(String sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/
  @ApiModelProperty(value = "")
  public String getSort() {
    return sort;
  }

  public void setSort(String sort) {
    this.sort = sort;
  }

  public GetPreferencesData sortOrder(String sortOrder) {
    this.sortOrder = sortOrder;
    return this;
  }

   /**
   * Get sortOrder
   * @return sortOrder
  **/
  @ApiModelProperty(value = "")
  public String getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(String sortOrder) {
    this.sortOrder = sortOrder;
  }

  public GetPreferencesData status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public GetPreferencesData searchString(String searchString) {
    this.searchString = searchString;
    return this;
  }

   /**
   * Get searchString
   * @return searchString
  **/
  @ApiModelProperty(value = "")
  public String getSearchString() {
    return searchString;
  }

  public void setSearchString(String searchString) {
    this.searchString = searchString;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPreferencesData getPreferencesData = (GetPreferencesData) o;
    return Objects.equals(this.id, getPreferencesData.id) &&
        Objects.equals(this.user, getPreferencesData.user) &&
        Objects.equals(this.tableName, getPreferencesData.tableName) &&
        Objects.equals(this.title, getPreferencesData.title) &&
        Objects.equals(this.columnsVisible, getPreferencesData.columnsVisible) &&
        Objects.equals(this.sort, getPreferencesData.sort) &&
        Objects.equals(this.sortOrder, getPreferencesData.sortOrder) &&
        Objects.equals(this.status, getPreferencesData.status) &&
        Objects.equals(this.searchString, getPreferencesData.searchString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, user, tableName, title, columnsVisible, sort, sortOrder, status, searchString);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPreferencesData {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    columnsVisible: ").append(toIndentedString(columnsVisible)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    searchString: ").append(toIndentedString(searchString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

