/*
 * directus.io
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.directus.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetSettingsDataFiles
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T21:48:16.590Z")
public class GetSettingsDataFiles {
  @SerializedName("allowed_thumbnails")
  private String allowedThumbnails = null;

  @SerializedName("thumbnail_quality")
  private String thumbnailQuality = null;

  @SerializedName("thumbnail_size")
  private String thumbnailSize = null;

  @SerializedName("file_naming")
  private String fileNaming = null;

  @SerializedName("thumbnail_crop_enabled")
  private String thumbnailCropEnabled = null;

  @SerializedName("youtube_api_key")
  private String youtubeApiKey = null;

  public GetSettingsDataFiles allowedThumbnails(String allowedThumbnails) {
    this.allowedThumbnails = allowedThumbnails;
    return this;
  }

   /**
   * Get allowedThumbnails
   * @return allowedThumbnails
  **/
  @ApiModelProperty(value = "")
  public String getAllowedThumbnails() {
    return allowedThumbnails;
  }

  public void setAllowedThumbnails(String allowedThumbnails) {
    this.allowedThumbnails = allowedThumbnails;
  }

  public GetSettingsDataFiles thumbnailQuality(String thumbnailQuality) {
    this.thumbnailQuality = thumbnailQuality;
    return this;
  }

   /**
   * Get thumbnailQuality
   * @return thumbnailQuality
  **/
  @ApiModelProperty(value = "")
  public String getThumbnailQuality() {
    return thumbnailQuality;
  }

  public void setThumbnailQuality(String thumbnailQuality) {
    this.thumbnailQuality = thumbnailQuality;
  }

  public GetSettingsDataFiles thumbnailSize(String thumbnailSize) {
    this.thumbnailSize = thumbnailSize;
    return this;
  }

   /**
   * Get thumbnailSize
   * @return thumbnailSize
  **/
  @ApiModelProperty(value = "")
  public String getThumbnailSize() {
    return thumbnailSize;
  }

  public void setThumbnailSize(String thumbnailSize) {
    this.thumbnailSize = thumbnailSize;
  }

  public GetSettingsDataFiles fileNaming(String fileNaming) {
    this.fileNaming = fileNaming;
    return this;
  }

   /**
   * Get fileNaming
   * @return fileNaming
  **/
  @ApiModelProperty(value = "")
  public String getFileNaming() {
    return fileNaming;
  }

  public void setFileNaming(String fileNaming) {
    this.fileNaming = fileNaming;
  }

  public GetSettingsDataFiles thumbnailCropEnabled(String thumbnailCropEnabled) {
    this.thumbnailCropEnabled = thumbnailCropEnabled;
    return this;
  }

   /**
   * Get thumbnailCropEnabled
   * @return thumbnailCropEnabled
  **/
  @ApiModelProperty(value = "")
  public String getThumbnailCropEnabled() {
    return thumbnailCropEnabled;
  }

  public void setThumbnailCropEnabled(String thumbnailCropEnabled) {
    this.thumbnailCropEnabled = thumbnailCropEnabled;
  }

  public GetSettingsDataFiles youtubeApiKey(String youtubeApiKey) {
    this.youtubeApiKey = youtubeApiKey;
    return this;
  }

   /**
   * Get youtubeApiKey
   * @return youtubeApiKey
  **/
  @ApiModelProperty(value = "")
  public String getYoutubeApiKey() {
    return youtubeApiKey;
  }

  public void setYoutubeApiKey(String youtubeApiKey) {
    this.youtubeApiKey = youtubeApiKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSettingsDataFiles getSettingsDataFiles = (GetSettingsDataFiles) o;
    return Objects.equals(this.allowedThumbnails, getSettingsDataFiles.allowedThumbnails) &&
        Objects.equals(this.thumbnailQuality, getSettingsDataFiles.thumbnailQuality) &&
        Objects.equals(this.thumbnailSize, getSettingsDataFiles.thumbnailSize) &&
        Objects.equals(this.fileNaming, getSettingsDataFiles.fileNaming) &&
        Objects.equals(this.thumbnailCropEnabled, getSettingsDataFiles.thumbnailCropEnabled) &&
        Objects.equals(this.youtubeApiKey, getSettingsDataFiles.youtubeApiKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowedThumbnails, thumbnailQuality, thumbnailSize, fileNaming, thumbnailCropEnabled, youtubeApiKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSettingsDataFiles {\n");
    
    sb.append("    allowedThumbnails: ").append(toIndentedString(allowedThumbnails)).append("\n");
    sb.append("    thumbnailQuality: ").append(toIndentedString(thumbnailQuality)).append("\n");
    sb.append("    thumbnailSize: ").append(toIndentedString(thumbnailSize)).append("\n");
    sb.append("    fileNaming: ").append(toIndentedString(fileNaming)).append("\n");
    sb.append("    thumbnailCropEnabled: ").append(toIndentedString(thumbnailCropEnabled)).append("\n");
    sb.append("    youtubeApiKey: ").append(toIndentedString(youtubeApiKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

