/*
 * directus.io
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.directus.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetSettingsDataGlobal
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T21:48:16.590Z")
public class GetSettingsDataGlobal {
  @SerializedName("cms_user_auto_sign_out")
  private String cmsUserAutoSignOut = null;

  @SerializedName("project_name")
  private String projectName = null;

  @SerializedName("project_url")
  private String projectUrl = null;

  @SerializedName("cms_color")
  private String cmsColor = null;

  @SerializedName("rows_per_page")
  private String rowsPerPage = null;

  @SerializedName("cms_thumbnail_url")
  private String cmsThumbnailUrl = null;

  public GetSettingsDataGlobal cmsUserAutoSignOut(String cmsUserAutoSignOut) {
    this.cmsUserAutoSignOut = cmsUserAutoSignOut;
    return this;
  }

   /**
   * Get cmsUserAutoSignOut
   * @return cmsUserAutoSignOut
  **/
  @ApiModelProperty(value = "")
  public String getCmsUserAutoSignOut() {
    return cmsUserAutoSignOut;
  }

  public void setCmsUserAutoSignOut(String cmsUserAutoSignOut) {
    this.cmsUserAutoSignOut = cmsUserAutoSignOut;
  }

  public GetSettingsDataGlobal projectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

   /**
   * Get projectName
   * @return projectName
  **/
  @ApiModelProperty(value = "")
  public String getProjectName() {
    return projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public GetSettingsDataGlobal projectUrl(String projectUrl) {
    this.projectUrl = projectUrl;
    return this;
  }

   /**
   * Get projectUrl
   * @return projectUrl
  **/
  @ApiModelProperty(value = "")
  public String getProjectUrl() {
    return projectUrl;
  }

  public void setProjectUrl(String projectUrl) {
    this.projectUrl = projectUrl;
  }

  public GetSettingsDataGlobal cmsColor(String cmsColor) {
    this.cmsColor = cmsColor;
    return this;
  }

   /**
   * Get cmsColor
   * @return cmsColor
  **/
  @ApiModelProperty(value = "")
  public String getCmsColor() {
    return cmsColor;
  }

  public void setCmsColor(String cmsColor) {
    this.cmsColor = cmsColor;
  }

  public GetSettingsDataGlobal rowsPerPage(String rowsPerPage) {
    this.rowsPerPage = rowsPerPage;
    return this;
  }

   /**
   * Get rowsPerPage
   * @return rowsPerPage
  **/
  @ApiModelProperty(value = "")
  public String getRowsPerPage() {
    return rowsPerPage;
  }

  public void setRowsPerPage(String rowsPerPage) {
    this.rowsPerPage = rowsPerPage;
  }

  public GetSettingsDataGlobal cmsThumbnailUrl(String cmsThumbnailUrl) {
    this.cmsThumbnailUrl = cmsThumbnailUrl;
    return this;
  }

   /**
   * Get cmsThumbnailUrl
   * @return cmsThumbnailUrl
  **/
  @ApiModelProperty(value = "")
  public String getCmsThumbnailUrl() {
    return cmsThumbnailUrl;
  }

  public void setCmsThumbnailUrl(String cmsThumbnailUrl) {
    this.cmsThumbnailUrl = cmsThumbnailUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSettingsDataGlobal getSettingsDataGlobal = (GetSettingsDataGlobal) o;
    return Objects.equals(this.cmsUserAutoSignOut, getSettingsDataGlobal.cmsUserAutoSignOut) &&
        Objects.equals(this.projectName, getSettingsDataGlobal.projectName) &&
        Objects.equals(this.projectUrl, getSettingsDataGlobal.projectUrl) &&
        Objects.equals(this.cmsColor, getSettingsDataGlobal.cmsColor) &&
        Objects.equals(this.rowsPerPage, getSettingsDataGlobal.rowsPerPage) &&
        Objects.equals(this.cmsThumbnailUrl, getSettingsDataGlobal.cmsThumbnailUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cmsUserAutoSignOut, projectName, projectUrl, cmsColor, rowsPerPage, cmsThumbnailUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSettingsDataGlobal {\n");
    
    sb.append("    cmsUserAutoSignOut: ").append(toIndentedString(cmsUserAutoSignOut)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    projectUrl: ").append(toIndentedString(projectUrl)).append("\n");
    sb.append("    cmsColor: ").append(toIndentedString(cmsColor)).append("\n");
    sb.append("    rowsPerPage: ").append(toIndentedString(rowsPerPage)).append("\n");
    sb.append("    cmsThumbnailUrl: ").append(toIndentedString(cmsThumbnailUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

