/*
 * directus.io
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.directus.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.directus.client.model.GetTableRowsData;
import io.directus.client.model.GetTableRowsMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GetTableRows
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T21:48:16.590Z")
public class GetTableRows {
  @SerializedName("meta")
  private GetTableRowsMeta meta = null;

  @SerializedName("data")
  private List<GetTableRowsData> data = null;

  public GetTableRows meta(GetTableRowsMeta meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @ApiModelProperty(value = "")
  public GetTableRowsMeta getMeta() {
    return meta;
  }

  public void setMeta(GetTableRowsMeta meta) {
    this.meta = meta;
  }

  public GetTableRows data(List<GetTableRowsData> data) {
    this.data = data;
    return this;
  }

  public GetTableRows addDataItem(GetTableRowsData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<GetTableRowsData>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public List<GetTableRowsData> getData() {
    return data;
  }

  public void setData(List<GetTableRowsData> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetTableRows getTableRows = (GetTableRows) o;
    return Objects.equals(this.meta, getTableRows.meta) &&
        Objects.equals(this.data, getTableRows.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTableRows {\n");
    
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

