#import <Foundation/Foundation.h>
#import <JSONModel/JSONValueTransformer.h>

/**
* directus.io
* API for directus.io
*
* OpenAPI spec version: 1.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface JSONValueTransformer (ISO8601)

@end
