=begin
#directus.io

#API for directus.io

OpenAPI spec version: 1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.0-SNAPSHOT

=end

# Common files
require 'directus_sdk/api_client'
require 'directus_sdk/api_error'
require 'directus_sdk/version'
require 'directus_sdk/configuration'

# Models
require 'directus_sdk/models/get_activity'
require 'directus_sdk/models/get_activity_data'
require 'directus_sdk/models/get_activity_meta'
require 'directus_sdk/models/get_bookmark'
require 'directus_sdk/models/get_bookmarks'
require 'directus_sdk/models/get_bookmarks_data'
require 'directus_sdk/models/get_bookmarks_meta'
require 'directus_sdk/models/get_file'
require 'directus_sdk/models/get_files'
require 'directus_sdk/models/get_files_data'
require 'directus_sdk/models/get_group'
require 'directus_sdk/models/get_groups'
require 'directus_sdk/models/get_groups_data'
require 'directus_sdk/models/get_groups_data_data'
require 'directus_sdk/models/get_groups_data_meta'
require 'directus_sdk/models/get_message'
require 'directus_sdk/models/get_messages'
require 'directus_sdk/models/get_messages_data'
require 'directus_sdk/models/get_messages_meta'
require 'directus_sdk/models/get_messages_responses'
require 'directus_sdk/models/get_preferences'
require 'directus_sdk/models/get_preferences_data'
require 'directus_sdk/models/get_privileges'
require 'directus_sdk/models/get_privileges_data'
require 'directus_sdk/models/get_privileges_for_table'
require 'directus_sdk/models/get_settings'
require 'directus_sdk/models/get_settings_data'
require 'directus_sdk/models/get_settings_data_files'
require 'directus_sdk/models/get_settings_data_global'
require 'directus_sdk/models/get_settings_for'
require 'directus_sdk/models/get_settings_for_meta'
require 'directus_sdk/models/get_table'
require 'directus_sdk/models/get_table_column'
require 'directus_sdk/models/get_table_column_data'
require 'directus_sdk/models/get_table_columns'
require 'directus_sdk/models/get_table_columns_data'
require 'directus_sdk/models/get_table_data'
require 'directus_sdk/models/get_table_row'
require 'directus_sdk/models/get_table_rows'
require 'directus_sdk/models/get_table_rows_data'
require 'directus_sdk/models/get_table_rows_meta'
require 'directus_sdk/models/get_tables'
require 'directus_sdk/models/get_tables_data'
require 'directus_sdk/models/get_tables_meta'

# APIs
require 'directus_sdk/api/activity_api'
require 'directus_sdk/api/bookmarks_api'
require 'directus_sdk/api/files_api'
require 'directus_sdk/api/groups_api'
require 'directus_sdk/api/messages_api'
require 'directus_sdk/api/preferences_api'
require 'directus_sdk/api/settings_api'
require 'directus_sdk/api/tables_api'
require 'directus_sdk/api/utils_api'

module DirectusSDK
  class << self
    # Customize default settings for the SDK using block.
    #   DirectusSDK.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
