/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package directussdk

type GetPrivilegesData struct {

	Id int32 `json:"id,omitempty"`

	TableName string `json:"table_name,omitempty"`

	GroupId int32 `json:"group_id,omitempty"`

	ReadFieldBlacklist string `json:"read_field_blacklist,omitempty"`

	WriteFieldBlacklist string `json:"write_field_blacklist,omitempty"`

	NavListed int32 `json:"nav_listed,omitempty"`

	StatusId int32 `json:"status_id,omitempty"`

	AllowView int32 `json:"allow_view,omitempty"`

	AllowAdd int32 `json:"allow_add,omitempty"`

	AllowEdit int32 `json:"allow_edit,omitempty"`

	AllowDelete int32 `json:"allow_delete,omitempty"`

	AllowAlter int32 `json:"allow_alter,omitempty"`
}
