/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package directussdk

type GetMessagesData struct {

	Id int32 `json:"id,omitempty"`

	From int32 `json:"from,omitempty"`

	Subject string `json:"subject,omitempty"`

	Message string `json:"message,omitempty"`

	Attachment string `json:"attachment,omitempty"`

	Datetime string `json:"datetime,omitempty"`

	ResponseTo string `json:"response_to,omitempty"`

	Read int32 `json:"read,omitempty"`

	Responses *GetMessagesResponses `json:"responses,omitempty"`

	Recipients string `json:"recipients,omitempty"`

	DateUpdated string `json:"date_updated,omitempty"`
}
