/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package directussdk

type GetBookmarksData struct {

	Id int32 `json:"id,omitempty"`

	User int32 `json:"user,omitempty"`

	Title string `json:"title,omitempty"`

	Url string `json:"url,omitempty"`

	IconClass string `json:"icon_class,omitempty"`

	Active string `json:"active,omitempty"`

	Section string `json:"section,omitempty"`
}
