/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package directussdk

type GetMessagesMeta struct {

	Read int32 `json:"read,omitempty"`

	Unread int32 `json:"unread,omitempty"`

	Total int32 `json:"total,omitempty"`

	MaxId int32 `json:"max_id,omitempty"`

	Type_ string `json:"type,omitempty"`

	Table string `json:"table,omitempty"`
}
