/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package directussdk

type GetTableRowsData struct {

	Id int32 `json:"id,omitempty"`

	Active int32 `json:"active,omitempty"`
}
