/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package directussdk

type GetTableColumn struct {

	Meta *GetTablesMeta `json:"meta,omitempty"`

	Data *GetTableColumnData `json:"data,omitempty"`
}
