/* 
 * directus.io
 *
 * API for directus.io
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package directussdk

type GetSettingsDataFiles struct {

	AllowedThumbnails string `json:"allowed_thumbnails,omitempty"`

	ThumbnailQuality string `json:"thumbnail_quality,omitempty"`

	ThumbnailSize string `json:"thumbnail_size,omitempty"`

	FileNaming string `json:"file_naming,omitempty"`

	ThumbnailCropEnabled string `json:"thumbnail_crop_enabled,omitempty"`

	YoutubeApiKey string `json:"youtube_api_key,omitempty"`
}
